AWSTemplateFormatVersion: 2010-09-09
Description: |
  This cfn file is used for creating a template which runs S3 static 
  web-hosting using cloudfront distribution.
Parameters:

# domain name

  myDomainName:
    Description: kitten.aredodevops.com
    Type: String
    Default: kitten.aredodevops.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)


Resources:

# s3 bucket
  
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref myDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html


# s3 bucket policy

  myBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref myS3Bucket 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref myS3Bucket
                - /*
            Principal: '*'

# cloudfront distribution

  myCloudFrontDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref myDomainName

        Comment: kitten-aws-10-cfn
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
 
          TargetOriginId: kitten-cfn-10-cloudfront

          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2

        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            
            DomainName: !Select [ 2, !Split [ "/", !GetAtt myS3Bucket.WebsiteURL ] ]          # mybucket endpoint URL
            Id: kitten-cfn-10-cloudfront

        PriceClass: PriceClass_All

        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:340752807298:certificate/4d7726d8-77c0-4ea0-8bf3-403a94c092d1  # change this for you
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

# r53
  myRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: kitten-cloudformation-r53-integration
      HostedZoneId: Z01406513GMHIO1ECMEXY                                  # Change this for your r53 hosted zone id
      RecordSets:                # Do not provide the HostedZoneId if it is already defined in AWS::Route53::RecordSetGroup
        - AliasTarget:
            DNSName: !GetAtt myCloudFrontDist.DomainName
            HostedZoneId: Z2FDTNDATAQYW2                                    # it is global no need for change!!!
          Name: !Ref myDomainName
          Type: A

Outputs:

  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt myS3Bucket.WebsiteURL

  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt myCloudFrontDist.DomainName
    
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref myDomainName
    